name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: Build, test with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: |-
            ./restdocs-api-spec/build/reports/jacoco/test/jacocoTestReport.xml,
            ./restdocs-api-spec-gradle-plugin/build/reports/jacoco/test/jacocoTestReport.xml,
            ./restdocs-api-spec-jsonschema/build/reports/jacoco/test/jacocoTestReport.xml,
            ./restdocs-api-spec-mockmvc/build/reports/jacoco/test/jacocoTestReport.xml,
            ./restdocs-api-spec-openapi3-generator/build/reports/jacoco/test/jacocoTestReport.xml
          flags: tests
          name: main-tests
