name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  build:
    name: JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21', '25']
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up JDKs
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: 'temurin'
          java-version: |
            17
            ${{ matrix.java }}
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6

      - name: Build, test with Gradle
        run: ./gradlew -Dorg.gradle.java.installations.fromEnv=JAVA_HOME_17_X64 clean check testCodeCoverageReport :restdocs-api-spec-example:openapi3 --no-daemon

      - name: Upload coverage to Codecov
        if: matrix.java == '17'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          flags: tests
          name: main-tests-jdk-17
